### ISSUE TITLE
feat: 대시보드 상세화면 모달 연결

### ISSUE THREAD

**Issue by devjaesung** [13teamProject/Planit#102]
## ✨ Todo
- [ ]  '새로운 컬럼 추가하기' 버튼을 누르면 컬럼 추가하기 모달이 나타납니다.
- [ ]  각 컬럼의 '+' 버튼을 누르면 해당 컬럼 할 일 생성 모달이 나타납니다.
- [ ]  각 컬럼의 '톱니바퀴' 버튼을 누르면 컬럼 수정 모달이 나타납니다.
- [ ]  생성된 할 일 카드를 클릭하면 해당 카드 상세 모달이 나타납니다.
