### ISSUE TITLE
refactor: Header 수정

### ISSUE THREAD

**Issue by kim-hye-sun** [13teamProject/Planit#112]
## ✨ Todo
- [ ] 헤더에서 초대했을때 초대 내역에 반영 안됨
- [ ] 프로필 사진/ 프로필 닉네임 수정시 새로고침 해야 헤더에 반영
- [ ] 대시보드 관리에서 계정관리가 뜸 → 대시보드 이름이 나와야 함
- [ ] 헤더의 프로필 circle 여러개 있는 부분에 초대받은 사람만 보이게
- [ ] framer-motion 적용해보기 (아주 긴 싸움이 될 것 같습니다.)
