### ISSUE TITLE
fix: 사이드 메뉴 및 기타 수정

### ISSUE THREAD

**Issue by yeonilil** [13teamProject/Planit#114]
## ✨ Todo
- [x] 페이지네이션 수정
- [x] 사이드 메뉴 모바일 버전 토글 추가
- [x] 모바일 버전 hover 수정 (전체 영역으로)
- [x] 사이드 메뉴 무한 스크롤로 변경, 로딩 스피너도 적용해보기
- [x] edit 페이지 타이틀 수정
