### ISSUE TITLE
fix: 대시보드 상세화면 디자인 추가 및 카드 수정하기 렌더링 적용

### ISSUE THREAD

**Issue by devjaesung** [13teamProject/Planit#121]
## ✨ Todo
- [x] 컬럼 추가하기 가로 스크롤 적용
- [x] 태블릿 사이즈, 모바일 화면일 때 컬럼 추가하기 sticky 적용
- [x] 카드 수정 후 리렌더링 적용
