### ISSUE TITLE
fix: 대시보드 헤더, 사이드 메뉴 수정

### ISSUE THREAD

**Issue by yeonilil** [13teamProject/Planit#57]
## ✨ Todo
- [x] 대시보드 헤더 편집페이지 Title 수정
- [x] Type들 파일로 분리 
- [x] 대시보드 헤더 정렬 수정
- [x] Profile Circle 데이터(API 연결)
