### ISSUE TITLE
feat: 대시보드 관리 - 대시보드 이름, 컬러 수정 작업

### ISSUE THREAD

**Issue by kim-hye-sun** [13teamProject/Planit#64]
## ✨ Todo
- [ ] 대시정보 UI 작업
- [ ] 대시보드 정보 가져오기
- [ ] 대시보드 이름, 컬러 수정
